version: '3.9'

services:
  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
      - TZ=Europe/Paris
    ports:
      # - "8000:8000"             # HTTP Web Interface for Crafty
      # - "8443:8443"             # HTTPS Web Interface for Crafty
      - "8123:8123"               # Dynmap Plugin (if used)
      - "19132:19132/udp"         # Bedrock server support
      - "25500-25600:25500-25600" # Minecraft server ports
    volumes:
      - /data/docker/crafty/backups:/crafty/backups   # Backups directory
      - /data/docker/crafty/logs:/crafty/logs         # Logs directory
      - /data/docker/crafty/servers:/crafty/servers   # Minecraft server files
      - /data/docker/crafty/config:/crafty/app/config # Crafty configuration
      - /data/docker/crafty/import:/crafty/import     # Import/export directory
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.crafty.rule=Host(`crafty.edj-labs.com`)"
        - "traefik.http.services.crafty.loadbalancer.server.port=8443"
        - "traefik.http.routers.crafty.tls=true"
        - "traefik.http.routers.crafty.tls.certresolver=letsencrypt"
        - "traefik.http.services.crafty.loadbalancer.server.scheme=https"
        - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"

networks:
  traefik-public:
    external: true
